### ISSUE TITLE
How do you use http to trigger doorbell button? Nothing in the Wiki/Readme

### ISSUE THREAD

**Issue by jsiegenthaler** [Sunoo/homebridge-camera-ffmpeg#697] opened 2020-07-28 06:47 UTC
**Describe The Problem:**
The description states:
`doorbell: Exposes the doorbell device for this camera. This can be triggered with the dummy switches, MQTT messages, or via HTTP, depending on what features are enabled in the config. (Default: false)`

I would like to use a http command to activate the doorbell trigger button, but I see no instructions on how to do so

**Homebridge Config:**

```json
    {
                    "name": "Front Door FFMPEG",
                    "manufacturer": "xxxx",
                    "model": "xxxx",
                    "serialNumber": "1234",
                    "firmwareRevision": "1.0",
                    "motion": true,
                    "motionTimeout": 1,
                    "doorbell": true,
                    "doorbellSwitch": true,
                    "switches": true,
                    "videoConfig": {
                        "source": "-re -ignore_loop 0 -i file:///home/pi/Public/fuo.gif",
                        "maxStreams": 2,
                        "maxWidth": 1280,
                        "maxHeight": 720,
                        "maxFPS": 10,
                        "maxBitrate": 300,
                        "vcodec": "libx264",
                        "audio": false,
                        "packetSize": 1316,
                        "vflip": false,
                        "hflip": false,
                        "debug": false
                    }
                }
```

**Environment:**

* **Node.js Version**:   v12.18.3
* **NPM Version**:  v6.14.7
* **Homebridge Version**:  1.2.0-beta.31
* **Homebridge Camera FFmpeg Version**:  homebridge-camera-ffmpeg v2.4.2
* **Homebridge Config UI X Plugin Version**: homebridge-config-ui-x v4.24.0
* **Operating System**:  Raspbian GNU/Linux Buster (10)

**Comment by Sunoo** [comment] 2020-07-28 12:42
It’s mentioned in the Wiki here: https://github.com/Sunoo/homebridge-camera-ffmpeg/wiki/HTTP-Motion#usage

If there is anything I can do to clarify that, please let me know.

**Comment by jsiegenthaler** [comment] 2020-07-28 16:19
Thanks Sunnoo. I did actually find it eventually, but it was rather "hidden".

I was browsing your documentation looking for hyperlinks in the text, and missed the fact that a Wiki table of contents existed on the right hand side of the page. Eventually I found it.

It would potentially help me and others like me to find the right Wiki page if you hyperlinked it more.
May I suggest some extra hyperlinks to the Wiki page:

Page: https://www.npmjs.com/package/homebridge-camera-ffmpeg
Add a Wiki hyperlink to this text to hyperlink (highlighted)
motion: Exposes the motion sensor for this camera. This can be triggered with the dummy switches, MQTT messages, or **_via HTTP_**, depending on what features are enabled in the config. (Default: false)
 Hyperlink to https://github.com/Sunoo/homebridge-camera-ffmpeg/wiki/HTTP-Motion

And likewise, same page, some hyperlink:
doorbell: Exposes the doorbell device for this camera. This can be triggered with the dummy switches, MQTT messages, or **_via HTTP_**, depending on what features are enabled in the config. (Default: false)

You could also do similar hyperlinks to the MQTT wiki pages.

**Comment by Sunoo** [comment] 2020-07-28 16:35
Great idea, I’ll add links in those locations on the GitHub page this afternoon. I can’t update the NPM page until I push the next release, but it will be included then.

**Comment by jsiegenthaler** [comment] 2020-07-28 16:46
Hmmm, I tried and nothing happened. I changed the config and restarted homebridge, but cannot get camera-ffmpeg to respond to the http command

I sent this http command from my broswer
http://192.168.0.171:8080/doorbell?Front%20Door%20FFMPEG
Browser said: This site can’t be reached 192.168.0.171 refused to connect.

My config is currently:
 ```
              {
                    "name": "Front Door FFMPEG",
                    "manufacturer": "Jochen",
                    "model": "Video Doorbell",
                    "serialNumber": "1234",
                    "firmwareRevision": "1.0",
                    "porthttp": "8080",
                    "motion": true,
                    "motionTimeout": 1,
                    "doorbell": true,
                    "doorbellSwitch": true,
                    "switches": true,
                    "videoConfig": {
                        "source": "-re -ignore_loop 0 -i file:///home/pi/Public/fuo.gif",
                        "stillImageSource": "-i file:///home/pi/Public/doorbell16x9.jpg",
                        "maxStreams": 2,
                        "maxWidth": 1280,
                        "maxHeight": 720,
                        "maxFPS": 10,
                        "maxBitrate": 300,
                        "vcodec": "libx264",
                        "audio": false,
                        "packetSize": 1316,
                        "vflip": false,
                        "hflip": false,
                        "debug": false
                    }
```

And tips?

**Comment by Sunoo** [comment] 2020-07-28 17:05
Yea, `porthttp` should be one level up in your config, at the same level as `platform`.

**Comment by jsiegenthaler** [comment] 2020-07-28 17:26
Thanks, working now.
I notice that the URL triggers the doorbell notification, but the appearance of the doorbell switch never changes.

The other plugin I tried, videodoorbell, which uses camera-ffmpeg as it's base, showed the doorbell switch turning on for 1 second, as a pushbutton switch. Optically this was much nicer. Perhaps you could activate the switch for 1s?

Also, I do not see the purpose of the pushbutton stateless switch: what is it for? Why is it there? I cannot find anything in the documentation for it, and I cannot understand its purpose.

**Comment by Sunoo** [comment] 2020-07-28 17:32
I’m not actually sure of the purpose of some of the doorbell stuff, it was largely added before my time working on the plugin. I do plan to go through that section of the code soon, maybe this weekend.

As for the switch states, that’s not a bad idea, I hadn’t done that because I didn’t expect anyone to be using both dummy switches and HTTP or MQTT at the same time.

**Comment by jsiegenthaler** [comment] 2020-07-28 18:16
OK. Let me tell you my scenario to give you some background as to my use case.
I live in an apartment with a 1980s analog video doorbell intercom, which can buzz open the building front door.

A 12V AC relay on my doorbell buzzer clicks in when the doorbell button is pressed and activates the Switch SW input of the Shelly1.
The Shelly1 SW input is decoupled from the relay and sends the http command direct to the camera-ffmpeg (previously I used webhooks and automations... now I don't need to, simpler is better...)
The camera-ffmpeg gets a video input from a motion gif, just to satisfy the Homekit requirement for motion video

I can then press the Unlock button on my Apple Device and the Cmd4 homebridge plugin LockMechanism connects to a Shelly plugin via automation to unlock the door via the same Shelly1.

I was hoping the LockMechanism would be tighter integrated, I've seen screenshots of earlier videodoorbells with a big UNLOCK button superimposed on the video. But I am not sure if this was deprecated in an earlier iOS version. If you could (experimentally) add in a LockMechanism that would be fantastic.  I'd be happy to test (if you can do beta versions...)

**Comment by Sunoo** [comment] 2020-07-28 20:55
I just tried adding a LockMechanism in my test setup, and it did not add any overlay or anything. It just shows up if you hit the icon with 4 boxes in the bottom right, but that's the same behavior as having a second accessory in the same room as the camera.

**Comment by Sunoo** [comment] 2020-07-28 22:56
> I notice that the URL triggers the doorbell notification, but the appearance of the doorbell switch never changes.

I just rewrote the handling of the triggers for motion and doorbell. Now no matter how they are triggered, the switches will turn on and off as well, as long as they are enabled in the config.

I also confirmed that the stateless button never actually did anything, so I just went ahead and removed it from the plugin.

I just pushed a beta with these changes. If you want to try them, you can install the beta with `sudo npm install -g homebridge-camera-ffmpeg@beta --unsafe-perm`. It'll probably be a day or so before I push a release with these changes.

**Comment by jsiegenthaler** [comment] 2020-07-30 07:29
Thanks @Sunnoo. I didn't get a chance to try the beta before you published the release. I just tried the release this morning and it works very well. Thanks a lot for your fast response!

May I suggest a couple of small enhancements?

Doorbell Button: currently the name is "Doorbell Trigger". I think a more fitting name is "Doorbell Button", as it is emulating the doorbell button. Yes, I know you can rename it, but a lot of people leave default names in place.

Response to http: When calling the http command, in my case http://192.168.0.171:8080/doorbell?Front%20Door, no response appears in the browser. You could send a small simple json response like {"success": true} or an error message if the plugin throws any error. This helps the user (me) know that the command was received when I am testing.
Currently, on my system, both  http://192.168.0.171:8080/doorbell?Front%20Door and  http://192.168.0.171:8080/doorbell?NonExistantName both produce identical responses. I cannot differentiate between success and error.
An unknown name should produce a response like "Error":"Camera name 'theUnknownName' not found", which would help the user realize he had a typo.

Log Entry: when the doorbell button is pushed, a log entry would be very useful. Apple use the text "<roomName> doorbell rang." in their notification, : so something like "<buttonName> pressed", which then causes the notification "Doorbell rang" would make sense.
[7/30/2020, 09:19:01] [Camera-ffmpeg] [<cameraName>] <buttonName> pressed
Tip: the videoDoorbell plugin which uses Camera-ffmpeg logs "Ding Dong!" and then it logs <buttonName> pressed
And something similar for the MotionDetector.

Great work!

**Comment by Sunoo** [comment] 2020-07-30 13:30
I'll consider changing the default name of the switch, but I think it's currently fairly descriptive. I think using "Doorbell Button" is potentially more confusing, as in most implementations I've seen that describes a Stateless Programmable Button that you can use to trigger automation when the button is pressed.

As for actually returning something to the browser on HTTP requests, that is something that I plan to do, I just haven't gotten around to it. I'd probably use HTTP response codes as well as a short message.

And the log entries, that information is currently logged, but only if you run Homebridge in debug mode. I really don't want to flood the logs with too much clutter, and I'm constantly trying to decide exactly what should make the cut.

**Comment by Sunoo** [comment] 2020-08-06 05:29
Just bumping this quickly so stalebot doesn’t snag it while I’m without power.

**Comment by somethingih** [comment] 2020-08-11 02:12
Im also seeing some issues with this. When I make the http request (http://homebridge:8080/motion?Front%20Porch%20Camera) nothing happens within homebridge.

I have tried making the request a few ways cURL, and from browser. Both return 200 with no issues, but on the Homebridge side nothing happens, no logging that says the motion trigger was tripped. not sure whats happening. any help would be great.

       ```
 {
            "name": "Camera FFmpeg",
            "porthttp": 8080,
            "localhttp": true,
            "cameras": [
                {
                    "name": "Front Porch Camera",
                    "model": "Raspi Cam",
                    "serialNumber": "1234",
                    "firmwareRevision": "1.0",
                    "motion": true,
                    "motionTimeout": 1,
                    "unbridge": true,
                    "videoConfig": {
                        "source": "-i http://porchcam:8081",
                        "stillImageSource": "-i http://porchcam/picture/1/current/",
                        "maxStreams": 3,
                        "maxWidth": 800,
                        "maxHeight": 480,
                        "maxFPS": 15,
                        "maxBitrate": 1000,
                        "vcodec": "h264_omx",
                        "packetSize": 564,
                        "debug": true
                    }
                }
            ],
            "platform": "Camera-ffmpeg"
        }
```

**Comment by Sunoo** [comment] 2020-08-11 13:42
Looks like I only have it set up to log motion notifications if you are running Homebridge itself in debug mode (I may change this in the future). That said, if you set the motionTimeout to a higher value (maybe 15 or something), you should be able to see the motion sensor trip by looking in the Home app when you make the call.

I also see you are using the `localhttp` option, which makes the server only listen to localhost on the device Homebridge is on. Though the fact that you're getting 200s back implies that you must be testing there already. I just wanted to mention it.

**Comment by somethingih** [comment] 2020-08-15 01:08
sorry, just got back to this. I made the change you suggested, setting the motionTimeout to 15. Im still not getting any notifications in Home app.

yeah the `localhttp`is due to a copy mistake, I was playing around. It is off.

**Comment by Sunoo** [comment] 2020-08-15 03:42
So the motion sensor never shows motion, if you watch the room in the Home app when you try to trigger it?

**Comment by somethingih** [comment] 2020-08-15 14:59
Yep, I make he request get 200 and watch homekit and nothing. I dont know whats happening.

**Comment by vladtsit** [comment] 2020-08-15 17:06
Hi! I have the same problem, motion is not activated by HTTP call and by MQTT call. How I can debut what is wrong?

**Comment by Sunoo** [comment] 2020-08-15 22:23
I'm working on adding some better responses to the HTTP stuff, so that should help in the future.

@vladtsit What HTTP requests are you making or what MQTT messages are you publishing? What does your config look like?

**Comment by Sunoo** [comment] 2020-08-15 23:47
So, fun fact. Apparently I had broken HTTP/MQTT automation at some point. I found the error while adding in some HTTP responses, and will be publishing a new version with fixes later tonight, once I've had some time to do a bit more testing to make sure I got it all.

**Comment by Sunoo** [comment] 2020-08-16 00:47
Okay, just published version 2.4.5 which should hopefully fix these issues as well as provide some useful responses to HTTP requests. Let me know if that resolves the issue for you.

**Comment by somethingih** [comment] 2020-08-16 02:32
@Sunoo, Iv been testing this and it seems to be an issue with the `automationHandler` function. However it's fetching `accessory` from homebridge doesnt seem to be working. No matter what I put in the request it kicks me to the else.

`Camera "c" not found.`

JS and TS arent really my forte

**Comment by Sunoo** [comment] 2020-08-16 02:34
@somethingih What URL are you trying to access? Is your camera really named "c" in your config?

**Comment by somethingih** [comment] 2020-08-16 02:38
Yeah, I just wanted to make it simple to I could rule out typo's.

`http://homebridge:8080/motion?c`

`                {
                    "name": "c",
                    "model": "Raspi Cam",
                    "serialNumber": "1234",
                    "firmwareRevision": "1.0",
                    "motion": true,
                    "motionTimeout": 15,
                    "unbridge": true,
                    "videoConfig": {
                        "source": "-i http://porchcam:8081",
                        "stillImageSource": "-i http://porchcam/picture/1/current",
                        "maxStreams": 3,
                        "maxWidth": 800,
                        "maxHeight": 480,
                        "maxFPS": 15,
                        "maxBitrate": 1000,
                        "vcodec": "h264_omx",
                        "packetSize": 564,
                        "debug": true
                    }
                }
`

**Comment by Sunoo** [comment] 2020-08-16 02:41
Okay, let me stick your exact config on my test setup and see if I can figure out what's going on.

I'm realizing now that I'm not sure I did any testing with `unbridge` set, so there is a decent chance that is where the issue lies.

**Comment by Sunoo** [comment] 2020-08-16 03:02
@somethingih Yea, that seemed to be the main problem. I just pushed a beta that should fix this issue, you can install it with `sudo npm install -g homebridge-camera-ffmpeg@beta --unsafe-perm`. Please test that when you have a chance, I'll keep my fingers crossed until then.

**Comment by vladtsit** [comment] 2020-08-16 07:48
Checked beta. Works as expected. Thank you!

**Comment by somethingih** [comment] 2020-08-16 14:48
@Sunoo, I also Checked the beta and things seem fine. I checked on Bridged and Unbridged configs. Everything seems good, Iv been able to hit every branch of that code. Motion, motion/reset, Doorbell, Error -`First directory level must be "motion" or "doorbell", got "TestError".`, and incorrect camera `Camera "notCam" not found.`

**Comment by Sunoo** [comment] 2020-08-16 14:51
Awesome, thanks for testing guys. I’ll likely push this to release later today.

**Closed** 2020-08-16 15:44 UTC
Labels: bug, enhancement
