### ISSUE TITLE
No audio

### ISSUE THREAD

**Issue by alebx** [Sunoo/homebridge-camera-ffmpeg#681] opened 2020-07-22 07:42 UTC
I've successfully set up my PS3 Eye to work with homebridge-camera-ffmpeg, but I struggle to get the audio stream to work. Audio and video are recorded when using on the cli `ffmpeg -re -f video4linux2 -i /dev/video0 -f alsa -ac 1 -ar 44100 -i sysdefault:CARD=CameraB409241 -t 5 out.mp4`. But in the homebridge setup no audio is streamed. What am I doing wrong? Also the audio mapping differs between cli and homebridge-camera-ffmpeg.

**Homebridge Config:**

```json
{
   "cameras":[
      {
         "name":"Cam",
         "videoConfig":{
            "source":"-re -f video4linux2 -i /dev/video0 -f alsa -ac 1 -ar 44100 -i sysdefault:CARD=CameraB409241",
            "stillImageSource":"-re -f video4linux2 -ss 0.9 -i /dev/video0 -vframes 1",
            "maxStreams":2,
            "maxWidth":1920,
            "maxHeight":1080,
            "maxFPS":30,
            "audio":true,
            "mapaudio":"1:0",
            "debug":true
         }
      }
   ],
   "platform":"Camera-ffmpeg"
}
```

**Screenshots:**

**Environment:**

* **Node.js Version**: v12.18.2
* **NPM Version**: v6.14.6
* **Homebridge Version**: v1.1.1
* **Homebridge Camera FFmpeg Version**:  v2.3.2
* **Homebridge Config UI X Plugin Version**: v4.23.2
* **Operating System**: Raspbian

**Comment by Sunoo** [comment] 2020-07-22 13:10
That looks likely to be correct, especially if it's working from the terminal. Can you post your Homebridge logs as well as the output of `arecord -L` please? That should help me see what's going wrong. I also believe I have a PS3 Eye around here somewhere, I'll see if I can find it and recreate your problem.

Also, this isn't the cause of your problem, but please don't use `-re` in your source. It is not meant to be used with live sources.

**Comment by alebx** [comment] 2020-07-22 15:04
Thanks for your fast response here are my outputs:

**arecord -L**
```
null
    Discard all samples (playback) or generate zero samples (capture)
jack
    JACK Audio Connection Kit
pulse
    PulseAudio Sound Server
array
softvol
cap
default
usbstream:CARD=Headphones
    bcm2835 Headphones
    USB Stream Output
sysdefault:CARD=CameraB409241
    USB Camera-B4.09.24.1, USB Audio
    Default Audio Device
front:CARD=CameraB409241,DEV=0
    USB Camera-B4.09.24.1, USB Audio
    Front speakers
surround21:CARD=CameraB409241,DEV=0
    USB Camera-B4.09.24.1, USB Audio
    2.1 Surround output to Front and Subwoofer speakers
surround40:CARD=CameraB409241,DEV=0
    USB Camera-B4.09.24.1, USB Audio
    4.0 Surround output to Front and Rear speakers
surround41:CARD=CameraB409241,DEV=0
    USB Camera-B4.09.24.1, USB Audio
    4.1 Surround output to Front, Rear and Subwoofer speakers
surround50:CARD=CameraB409241,DEV=0
    USB Camera-B4.09.24.1, USB Audio
    5.0 Surround output to Front, Center and Rear speakers
surround51:CARD=CameraB409241,DEV=0
    USB Camera-B4.09.24.1, USB Audio
    5.1 Surround output to Front, Center, Rear and Subwoofer speakers
surround71:CARD=CameraB409241,DEV=0
    USB Camera-B4.09.24.1, USB Audio
    7.1 Surround output to Front, Center, Side, Rear and Woofer speakers
iec958:CARD=CameraB409241,DEV=0
    USB Camera-B4.09.24.1, USB Audio
    IEC958 (S/PDIF) Digital Audio Output
dmix:CARD=CameraB409241,DEV=0
    USB Camera-B4.09.24.1, USB Audio
    Direct sample mixing device
dsnoop:CARD=CameraB409241,DEV=0
    USB Camera-B4.09.24.1, USB Audio
    Direct sample snooping device
hw:CARD=CameraB409241,DEV=0
    USB Camera-B4.09.24.1, USB Audio
    Direct hardware device without any conversions
plughw:CARD=CameraB409241,DEV=0
    USB Camera-B4.09.24.1, USB Audio
    Hardware device with all software conversions
usbstream:CARD=CameraB409241
    USB Camera-B4.09.24.1
    USB Stream Output
```

**Homebridge log:**
```
[7/22/2020, 15:22:30] [Camera-ffmpeg] Starting Poppycam video stream (1280x720, 30 fps, 299 kbps, 1316 mtu)... debug enabled
[7/22/2020, 15:22:30] [Camera-ffmpeg] Poppycam command: ffmpeg -f video4linux2 -i /dev/video0 -f alsa -ac 1 -ar 44100 -i sysdefault:CARD=CameraB409241 -map 0:0 -vcodec libx264 -pix_fmt yuv420p -r 30 -f rawvideo -preset ultrafast -tune zerolatency -vf scale=1280:720 -b:v 299k -bufsize 598k -maxrate 299k -payload_type 99 -ssrc 7876155 -f rtp -srtp_out_suite AES_CM_128_HMAC_SHA1_80 -srtp_out_params XtRZIZPqPigmdGuZN/B2eQK8dyenebMnAkVCIN2D srtp://192.168.0.104:53118?rtcpport=53118&localrtcpport=53118&pkt_size=1316 -map 1:0 -acodec libfdk_aac -profile:a aac_eld -flags +global_header -f null -ar 16k -b:a 24k -bufsize 24k -ac 1 -payload_type 110 -ssrc 15084428 -f rtp -srtp_out_suite AES_CM_128_HMAC_SHA1_80 -srtp_out_params WmOp3tZEvmRWiATO4teRvHrPAudIy92EZtZ+1b1Z srtp://192.168.0.104:59899?rtcpport=59899&localrtcpport=59899&pkt_size=188 -loglevel level+verbose
[7/22/2020, 15:22:30] [Camera-ffmpeg] Poppycam: [info] ffmpeg version 4.2.2-d1e8be3 Copyright (c) 2000-2019 the FFmpeg developers
[info]   built with gcc 6.3.0 (Raspbian 6.3.0-18+rpi1+deb9u1) 20170516
[info]   configuration: --pkgconfigdir=/build/workspace/lib/pkgconfig --prefix=/build/workspace --pkg-config-flags=--static --extra-cflags=-I/build/workspace/include --extra-ldflags=-L/build/workspace/lib --extra-libs='-lpthread -lm' --enable-static --disable-debug --disable-shared --disable-ffplay --disable-doc --enable-openssl --enable-gpl --enable-version3 --enable-nonfree --enable-pthreads --enable-libvpx --enable-libmp3lame --enable-libopus --enable-libtheora --enable-libvorbis --enable-libx264 --enable-runtime-cpudetect --enable-libfdk-aac --enable-avfilter --enable-libopencore_amrwb --enable-libopencore_amrnb --enable-filters --enable-decoder=h264 --enable-network --enable-protocol=tcp --enable-libspeex --enable-demuxer=rtsp --enable-omx-rpi --enable-mmal --enable-indev=alsa --enable-outdev=alsa

[7/22/2020, 15:22:30] [Camera-ffmpeg] Poppycam: [info]   libavutil      56. 31.100 / 56. 31.100
[info]   libavcodec     58. 54.100 / 58. 54.100
[info]   libavformat    58. 29.100 / 58. 29.100
[info]   libavdevice    58.  8.100 / 58.  8.100
[info]   libavfilter     7. 57.100 /  7. 57.100
[info]   libswscale      5.  5.100 /  5.  5.100
[info]   libswresample   3.  5.100 /  3.  5.100
[info]   libpostproc    55.  5.100 / 55.  5.100

[7/22/2020, 15:22:30] [Camera-ffmpeg] Poppycam: [video4linux2,v4l2 @ 0x386e350] [verbose] fd:3 capabilities:85200001
[video4linux2,v4l2 @ 0x386e350] [verbose] Querying the device for the current frame size
[video4linux2,v4l2 @ 0x386e350] [verbose] Setting frame size to 640x480

[7/22/2020, 15:22:31] [Camera-ffmpeg] Poppycam: [info] Input #0, video4linux2,v4l2, from '/dev/video0':
[info]   Duration: N/A, start: 3015.872829, bitrate: 147456 kb/s

[7/22/2020, 15:22:31] [Camera-ffmpeg] Poppycam: [info]     Stream #0:0: Video: rawvideo, 1 reference frame (YUY2 / 0x32595559), yuyv422, 640x480, 147456 kb/s, 30 fps, 30 tbr, 1000k tbn, 1000k tbc

[7/22/2020, 15:22:31] [Camera-ffmpeg] Poppycam: [warning] Guessed Channel Layout for Input Stream #1.0 : mono
[info] Input #1, alsa, from 'sysdefault:CARD=CameraB409241':
[info]   Duration: N/A, start: 1595427749.690853, bitrate: 
[7/22/2020, 15:22:31] [Camera-ffmpeg] Poppycam: 705 kb/s
[info]     Stream #1:0: Audio: pcm_s16le, 44100 Hz, mono, s16, 705 kb/s

[7/22/2020, 15:22:31] [Camera-ffmpeg] Poppycam: [info] Stream mapping:
[info]   Stream #0:0 -> #0:0 (rawvideo (native) -> h264 (libx264))
[info]   Stream #1:0 -> #1:0 (pcm_s16le (native) -> aac (libfdk_aac))
[info] Press [q] to stop, [?] for help

[7/22/2020, 15:22:31] [Camera-ffmpeg] Poppycam: [Parsed_scale_0 @ 0x38f9050] [verbose] w:1280 h:720 flags:'bicubic' interl:0

[7/22/2020, 15:22:31] [Camera-ffmpeg] Poppycam: [graph 0 input from stream 0:0 @ 0x390bc00] [verbose] w:640 h:480 pixfmt:yuyv422 tb:1/1000000 fr:30/1 sar:0/1 sws_param:flags=2

[7/22/2020, 15:22:31] [Camera-ffmpeg] Poppycam: [Parsed_scale_0 @ 0x38f9050] [verbose] w:640 h:480 fmt:yuyv422 sar:0/1 -> w:1280 h:720 fmt:yuv420p sar:0/1 flags:0x4

[7/22/2020, 15:22:31] [Camera-ffmpeg] Poppycam: [libx264 @ 0x38bf9b0] [info] using cpu capabilities: ARMv6 NEON

[7/22/2020, 15:22:31] [Camera-ffmpeg] Poppycam: [libx264 @ 0x38bf9b0] [info] profile Constrained Baseline, level 3.1, 4:2:0, 8-bit

[7/22/2020, 15:22:31] [Camera-ffmpeg] Poppycam: [info] Output #0, rtp, to 'srtp://192.168.0.104:53118?rtcpport=53118&localrtcpport=53118&pkt_size=1316':
[info]   Metadata:
[info]     encoder         : Lavf58.29.100
[info]     Stream #0:0: Video: h264 (libx264), 1 reference frame, yuv420p, 1280x720, q=-1--1, 299 kb/s, 30 fps, 90k tbn, 30 tbc
[info]     Metadata:
[info]       encoder         : Lavc58.54.100 libx264
[info]     Side data:
[info]       cpb: bitrate max/min/avg: 299000/0/299000 buffer size: 598000 vbv_delay: -1

[7/22/2020, 15:22:32] [Camera-ffmpeg] Poppycam: [graph_1_in_1_0 @ 0x3af81a0] [verbose] tb:1/44100 samplefmt:s16 samplerate:44100 chlayout:0x4

[7/22/2020, 15:22:32] [Camera-ffmpeg] Poppycam: [format_out_1_0 @ 0x3af8310] [verbose] auto-inserting filter 'auto_resampler_0' between the filter 'Parsed_anull_0' and the filter 'format_out_1_0'

[7/22/2020, 15:22:32] [Camera-ffmpeg] Poppycam: [auto_resampler_0 @ 0x3af97b0] [verbose] ch:1 chl:mono fmt:s16 r:44100Hz -> ch:1 chl:mono fmt:s16 r:16000Hz

[7/22/2020, 15:22:32] [Camera-ffmpeg] Poppycam: [info] Output #1, rtp, to 'srtp://192.168.0.104:59899?rtcpport=59899&localrtcpport=59899&pkt_size=188':
[info]   Metadata:
[info]     encoder         : Lavf58.29.100

[7/22/2020, 15:22:32] [Camera-ffmpeg] Poppycam: [info]     Stream #1:0: Audio: aac (libfdk_aac) (ELD), 16000 Hz, mono, s16, delay 288, 24 kb/s
[info]     Metadata:
[info]       encoder         : Lavc58.54.100 libfdk_aac

[7/22/2020, 15:22:32] [Camera-ffmpeg] Poppycam: [video4linux2,v4l2 @ 0x386e350] [warning] Thread message queue blocking; consider raising the thread_queue_size option (current value: 8)

[7/22/2020, 15:22:32] [Camera-ffmpeg] Poppycam: [info] frame=    5 fps=0.0 q=49.0 size=       6kB time=00:00:00.14 bitrate= 369.3kbits/s speed=0.246x    
[7/22/2020, 15:22:32] [Camera-ffmpeg] Poppycam: [alsa @ 0x3870eb0] [warning] Thread message queue blocking; consider raising the thread_queue_size option (current value: 8)

[7/22/2020, 15:22:32] [Camera-ffmpeg] Poppycam: [info] frame=    9 fps=7.7 q=47.0 size=       9kB time=00:00:00.33 bitrate= 224.2kbits/s speed=0.285x    
[7/22/2020, 15:22:33] [Camera-ffmpeg] Poppycam: [info] frame=   14 fps=7.9 q=46.0 size=      13kB time=00:00:00.52 bitrate= 198.4kbits/s speed=0.299x    
[7/22/2020, 15:22:34] [Camera-ffmpeg] Poppycam: [info] frame=   20 fps=8.6 q=44.0 size=      18kB time=00:00:00.65 bitrate= 224.3kbits/s speed=0.282x    
[7/22/2020, 15:22:34] [Camera-ffmpeg] Poppycam: [info] frame=   24 fps=8.2 q=44.0 size=      22kB time=00:00:00.84 bitrate= 211.5kbits/s speed=0.29x    
[7/22/2020, 15:22:35] [Camera-ffmpeg] Poppycam: [info] frame=   30 fps=8.6 q=44.0 size=      27kB time=00:00:00.98 bitrate= 222.4kbits/s speed=0.281x    
[7/22/2020, 15:22:36] [Camera-ffmpeg] Poppycam: [info] frame=   35 fps=8.5 q=43.0 size=      32kB time=00:00:01.31 bitrate= 199.1kbits/s speed=0.32x    
[7/22/2020, 15:22:36] [Camera-ffmpeg] Poppycam: [info] frame=   40 fps=8.5 q=43.0 size=      36kB time=00:00:01.31 bitrate= 223.9kbits/s [alsa @ 0x3870eb0] [warning] ALSA buffer xrun.

[7/22/2020, 15:22:36] [Camera-ffmpeg] Poppycam: [verbose] 
[7/22/2020, 15:22:36] [Camera-ffmpeg] Poppycam: *** 1 dup!

[7/22/2020, 15:22:36] [Camera-ffmpeg] Poppycam: [verbose] *** 3 dup!

[7/22/2020, 15:22:37] [Camera-ffmpeg] Poppycam: [verbose] *** 3 dup!

[7/22/2020, 15:22:37] [Camera-ffmpeg] Poppycam: [info] frame=   51 fps=9.5 q=40.0 size=      61kB time=00:00:01.77 bitrate= 282.6kbits/s dup=7 drop=0 speed=0.331x    
[7/22/2020, 15:22:37] [Camera-ffmpeg] Poppycam: [verbose] *** 2 dup!

[7/22/2020, 15:22:37] [Camera-ffmpeg] Poppycam: [verbose] *** 3 dup!

[7/22/2020, 15:22:37] [Camera-ffmpeg] Poppycam: [verbose] *** 2 dup!

[7/22/2020, 15:22:37] [Camera-ffmpeg] Poppycam: [info] frame=   61 fps= 10 q=40.0 size=      72kB time=00:00:02.27 bitrate= 261.1kbits/s dup=14 drop=0 speed=0.38x    
[7/22/2020, 15:22:38] [Camera-ffmpeg] Poppycam: [verbose] *** 2 dup!

[7/22/2020, 15:22:38] [Camera-ffmpeg] Poppycam: [verbose] *** 3 dup!

[7/22/2020, 15:22:38] [Camera-ffmpeg] Poppycam: [verbose] *** 2 dup!

[7/22/2020, 15:22:38] [Camera-ffmpeg] Poppycam: [info] frame=   71 fps= 11 q=40.0 size=      86kB time=00:00:02.33 bitrate= 303.4kbits/s dup=21 drop=0 speed=0.356x    
[7/22/2020, 15:22:38] [Camera-ffmpeg] Poppycam: [verbose] *** 2 dup!

[7/22/2020, 15:22:38] [Camera-ffmpeg] Poppycam: [verbose] *** 3 dup!

[7/22/2020, 15:22:38] [Camera-ffmpeg] Poppycam: [info] 
[7/22/2020, 15:22:38] [Camera-ffmpeg] Poppycam: frame=   78 fps= 11 q=40.0 size=      95kB time=00:00:02.90 bitrate= 269.5kbits/s dup=26 drop=0 speed=0.408x    
[7/22/2020, 15:22:38] [Camera-ffmpeg] Poppycam: [verbose] 
[7/22/2020, 15:22:38] [Camera-ffmpeg] Poppycam: *** 2 dup!

[7/22/2020, 15:22:39] [Camera-ffmpeg] Poppycam: [verbose] *** 3 dup!

[7/22/2020, 15:22:39] [Camera-ffmpeg] Poppycam: [verbose] *** 2 dup!

[7/22/2020, 15:22:39] [Camera-ffmpeg] Poppycam: [info] frame=   88 fps= 11 q=40.0 size=     106kB time=00:00:03.23 bitrate= 267.8kbits/s dup=33 drop=0 speed=0.42x    
[7/22/2020, 15:22:39] [Camera-ffmpeg] Poppycam: [verbose] 
[7/22/2020, 15:22:39] [Camera-ffmpeg] Poppycam: *** 3 dup!

[7/22/2020, 15:22:39] [Camera-ffmpeg] Poppycam: [verbose] *** 3 dup!

[7/22/2020, 15:22:40] [Camera-ffmpeg] Poppycam: [verbose] *** 3 dup!

[7/22/2020, 15:22:40] [Camera-ffmpeg] Poppycam: [alsa @ 0x3870eb0] [warning] ALSA buffer xrun.

[7/22/2020, 15:22:40] [Camera-ffmpeg] Poppycam: [info] frame=  100 fps= 12 q=40.0 size=     127kB time=00:00:03.40 bitrate= 305.9kbits/s dup=42 drop=0 speed=0.409x    
[7/22/2020, 15:22:40] [Camera-ffmpeg] Poppycam: [verbose] *** 2 dup!

[7/22/2020, 15:22:40] [Camera-ffmpeg] Poppycam: [libfdk_aac @ 0x38e5ab0] [warning] Queue input is backward in time

[7/22/2020, 15:22:40] [Camera-ffmpeg] Poppycam: [verbose] *** 2 dup!

[7/22/2020, 15:22:40] [Camera-ffmpeg] Poppycam: [rtp @ 0x38e46a0] [warning] Non-monotonous DTS in output stream 1:0; previous: 55191, current: 55125; changing to 55191. This may result in incorrect timestamps in the output file.
[libfdk_aac @ 0x38e5ab0] [warning] Queue input is backward in time

[7/22/2020, 15:22:40] [Camera-ffmpeg] Poppycam: [rtp @ 0x38e46a0] [warning] Non-monotonous DTS in output stream 1:0; previous: 55637, current: 55406; changing to 55637. This may result in incorrect timestamps in the output file.

[7/22/2020, 15:22:40] [Camera-ffmpeg] Poppycam: [verbose] *** 3 dup!

[7/22/2020, 15:22:40] [Camera-ffmpeg] Poppycam: [verbose] *** 2 dup!

[7/22/2020, 15:22:40] [Camera-ffmpeg] Poppycam: [info] frame=  113 fps= 13 q=40.0 size=     140kB time=00:00:03.75 bitrate= 305.5kbits/s dup=51 drop=0 speed=0.42x    
[7/22/2020, 15:22:40] [Camera-ffmpeg] Poppycam: [verbose] *** 3 dup!

[7/22/2020, 15:22:41] [Camera-ffmpeg] Poppycam: [verbose] *** 3 dup!

[7/22/2020, 15:22:41] [Camera-ffmpeg] Poppycam: [verbose] *** 3 dup!

[7/22/2020, 15:22:41] [Camera-ffmpeg] Poppycam: [info] frame=  125 fps= 13 q=40.0 size=     160kB time=00:00:04.98 bitrate= 263.4kbits/s dup=60 drop=0 speed=0.523x    
[7/22/2020, 15:22:41] [Camera-ffmpeg] Poppycam: [verbose] *** 2 dup!

[7/22/2020, 15:22:41] [Camera-ffmpeg] Poppycam: [verbose] *** 2 dup!

[7/22/2020, 15:22:41] [Camera-ffmpeg] Poppycam: [verbose] 
[7/22/2020, 15:22:41] [Camera-ffmpeg] Poppycam: *** 3 dup!

[7/22/2020, 15:22:42] [Camera-ffmpeg] Poppycam: [info] frame=  135 fps= 13 q=40.0 size=     172kB time=00:00:04.98 bitrate= 282.3kbits/s dup=67 drop=0 speed=0.494x    
[7/22/2020, 15:22:42] [Camera-ffmpeg] Poppycam: [verbose] 
[7/22/2020, 15:22:42] [Camera-ffmpeg] Poppycam: *** 3 dup!

[7/22/2020, 15:22:42] [Camera-ffmpeg] Poppycam: [verbose] *** 3 dup!

[7/22/2020, 15:22:42] [Camera-ffmpeg] Poppycam: [verbose] *** 2 dup!

[7/22/2020, 15:22:42] [Camera-ffmpeg] Poppycam: [info] frame=  146 fps= 14 q=40.0 size=     185kB time=00:00:04.98 bitrate= 303.9kbits/s dup=75 drop=0 speed=0.464x    
[7/22/2020, 15:22:42] [Camera-ffmpeg] Poppycam: [verbose] *** 2 dup!

[7/22/2020, 15:22:43] [Camera-ffmpeg] Poppycam: [verbose] 
[7/22/2020, 15:22:43] [Camera-ffmpeg] Poppycam: *** 3 dup!

[7/22/2020, 15:22:43] [Camera-ffmpeg] Poppycam: [alsa @ 0x3870eb0] [warning] ALSA buffer xrun.

[7/22/2020, 15:22:43] [Camera-ffmpeg] Poppycam: [info] frame=  153 fps= 13 q=40.0 size=     194kB time=00:00:05.96 bitrate= 266.2kbits/s dup=80 drop=0 speed=0.526x    
[7/22/2020, 15:22:43] [Camera-ffmpeg] Poppycam: [verbose] *** 3 dup!

[7/22/2020, 15:22:43] [Camera-ffmpeg] Poppycam: [verbose] *** 3 dup!

[7/22/2020, 15:22:43] [Camera-ffmpeg] Poppycam: [verbose] *** 7 dup!

[7/22/2020, 15:22:43] [Camera-ffmpeg] Poppycam: [verbose] *** 5 dup!

[7/22/2020, 15:22:44] [Camera-ffmpeg] Poppycam: [info] frame=  175 fps= 14 q=43.0 size=     246kB time=00:00:05.96 bitrate= 337.3kbits/s dup=98 drop=0 speed=0.492x    
[7/22/2020, 15:22:44] [Camera-ffmpeg] Poppycam: [verbose] *** 5 dup!

[7/22/2020, 15:22:44] [Camera-ffmpeg] Poppycam: [alsa @ 0x3870eb0] [warning] ALSA buffer xrun.

[7/22/2020, 15:22:44] [Camera-ffmpeg] Poppycam: [info] frame=  181 fps= 14 q=41.0 size=     252kB time=00:00:06.83 bitrate= 302.0kbits/s dup=103 drop=0 speed=0.54x    
[7/22/2020, 15:22:44] [Camera-ffmpeg] Poppycam: [verbose] *** 6 dup!

[7/22/2020, 15:22:44] [Camera-ffmpeg] Poppycam: [verbose] *** 4 dup!

[7/22/2020, 15:22:45] [Camera-ffmpeg] Poppycam: [verbose] *** 4 dup!

[7/22/2020, 15:22:45] [Camera-ffmpeg] Poppycam: [info] frame=  198 fps= 15 q=42.0 size=     276kB time=00:00:06.83 bitrate= 330.7kbits/s dup=117 drop=0 speed=0.518x    
[7/22/2020, 15:22:45] [Camera-ffmpeg] Stopped Poppycam video stream!
```

**Comment by alebx** [comment] 2020-07-22 15:14
Ok, now it seems to work better, I've added the thread_queue_size param: `"source": "-f video4linux2 -i /dev/video0 -thread_queue_size 512 -f alsa -ac 1 -ar 44100 -i sysdefault:CARD=CameraB409241"`.

But the whole thing lags very bad, but thats probably my raspberry pi 2's fault.

**Comment by Sunoo** [comment] 2020-07-22 15:15
Hmm... I'll definitely take a look for my PS3 Eye this afternoon and see if I can recreate this. I do have a different USB camera that is working with v4l2 and alsa through this plugin, and I have minor differences from what your config is.

This is your config, tweaked to look more like how my camera is set up, might be worth giving a shot.

```json
{
   "cameras":[
      {
         "name":"Cam",
         "videoConfig":{
            "source":"-re -f video4linux2 -i /dev/video0 -f alsa -ac 1 -i hw:CARD=CameraB409241",
            "stillImageSource":"-re -f video4linux2 -ss 0.9 -i /dev/video0 -vframes 1",
            "maxStreams":2,
            "maxWidth":1920,
            "maxHeight":1080,
            "maxFPS":30,
            "audio":true,
            "mapaudio":"1:0",
            "debug":true
         }
      }
   ],
   "platform":"Camera-ffmpeg"
}
```

**Comment by Sunoo** [comment] 2020-07-22 15:17
Oh, looks like you snuck in another reply while I was posting that. If you're running a Pi 2, you may wanna give setting `vcodec` to `h264_omx` a try. That will you the Pi's hardware acceleration to encode the video instead of doing it all in software.

**Comment by alebx** [comment] 2020-07-22 16:14
I think somethings wrong with my alsa config, I can somehow just access the `sysdefault:CARD=CameraB409241`...

Thanks for your help! Changing the `vcodec` really helped.

**Comment by Sunoo** [comment] 2020-07-22 17:23
Sure thing. Sounds like we can close this out now then.

**Closed by Sunoo** 2020-07-22 17:23 UTC
Labels: question
