### ISSUE TITLE
Snapshots Not working

### ISSUE THREAD

**Issue by muzzman1** [Sunoo/homebridge-camera-ffmpeg#1243] opened 2022-01-01 18:08 UTC
No changes, but now HomeKit snapshots not updating.  Live video works, but snapshots are stuck on later date.   Live video used to update snapshots, and that is not working either.  
    Come to think of it, Ring camera snapshots not working either.     
   Might be a system wide issue and not FFMpeg after all.

**Comment by Sunoo** [comment] 2022-01-01 18:10
As far as we can tell, this is an Apple problem, as even official HomeKit cameras seem to have this issue right now. I’ve heard you can get it working again temporarily by logging out and back in to iCloud, but I haven’t bothered. Hopefully the next iOS release resolves it.

**Comment by muzzman1** [comment] 2022-01-01 18:12
Ahh, thank you for the quick update!

**Comment by lishan89uc** [comment] 2022-01-04 18:30
For me the snapshot timer was stuck at  "now" and sometimes it is a black screen. However after testing with 2 iPads and 2 Apple TVs I've found that this is only happening on my iPhone 13 pm and the iPad 6th gen. Both of the Apple TVs and iPad pro was working. So I removed all 6 of my cameras and readded them. So far they are working like before. This includes my Ring camera. 
Side note: I checked immediately after updating to 3.1.4 and it was working fine, so this doesn't seem to be update related.

**Comment by EddyGitH** [comment] 2022-01-08 22:09
I had the same issue, re-added them and the snapshots are working fine now! ;-)
I hope the normal accessories will work better now also because they did not update very well, needed to end the programm and restart everytime.

**Comment by modi80** [comment] 2022-01-09 08:41
The same here. The problem appeared after updating to Hoobs 4. After deleting the camera and re-adding everything works like before.

**Comment by djsomi** [comment] 2022-01-15 08:03
Same here, nothing changed, and snapshot are show from days behind.

Disable/Enable plugin helps for a while. Hope Apple fix this. 
Does anyone knows what exactly wrong on apple side? Any link, discussion?

Thanks
Somi

**Comment by grzegorz914** [comment] 2022-01-15 08:50
This is iOS problem, I have updated to iOS 15.3-beta.2 and all working correct now.

**Comment by djsomi** [comment] 2022-01-15 10:38
> This is iOS problem, I have updated to iOS 15.3-beta.3 and all working correct now.

Yes I can confirm, no issue on my iPads, only seen on iOS.

**Comment by lishan89uc** [comment] 2022-01-15 10:47
> 

I think you meant 15.3 beta 2. I just want to add that if you removed and readd all of the cameras they will start working as normal again. Mine are still working and it has been 11 days. Also I can confirm this is probably not a homebridge-camera-ffmpeg problem since the same issue happened to 2 of my eufy 2k cameras with built in homekit compatibility and do not go through homebridge. Same solution just re-adding them they are working fine now.

**Comment by djsomi** [comment] 2022-01-15 10:50
> I think you meant 15.3 beta 2. I just want to add that if you removed and readd all of the cameras they will start working as normal again. Mine are still working and it has been 11 days. Also I can confirm this is probably not a homebridge-camera-ffmpeg problem since the same issue happened to 2 of my eufy 2k cameras with built in homekit compatibility and do not go through homebridge. Same solution just re-adding them they are working fine now.

They will stop again, it happened for me after 1-2 weeks again. So lets hope iOS 15.3 will fix it.

**Comment by jamie-2bit** [comment] 2022-01-20 09:28
Can confirm. This is happening to me too on iPhone 13 & iOS15.2.1

**Comment by danielherrington** [comment] 2022-02-01 17:27
Updated to 15.3 on iPhone 13 and issue resolved.  Will respond if it comes back in 1-2 weeks like the remove/re-add fix.

**Comment by Sunoo** [comment] 2022-02-01 17:29
I believe Apple even called this out as being fixed in 15.3. I know I've heard a bunch of reports in the discord that this seems to be resolved now too. In light of that, I'm going to close this out. If anyone hits this in the future (and is on 15.3 or newer), please open a new issue.

**Closed by Sunoo** 2022-02-01 17:29 UTC
