### ISSUE TITLE
No streaming, or max. about 5/10 sec. with latest updates

### ISSUE THREAD

**Issue by GermanyP** [Sunoo/homebridge-camera-ffmpeg#674] opened 2020-07-20 14:37 UTC
HI, with latest updates with no touch anything of my config, have a problems for streaming video to homekit, have attached all info:

            "name": "Cameras",
            "cameras": [
                {
                    "name": "Camara Comedor",
                    "videoConfig": {
                        "source": "-rtsp_transport tcp -i rtsp://XXXX.XXX.X.XX/unicast",
                        "stillImageSource": "-i rtsp://XXX.XX.XX/unicast -vframes 1 -r 1",
                        "maxStreams": 2,
                        "maxWidth": 720,
                        "maxHeight": 480,
                        "maxFPS": 10,
                        "maxBitrate": 500,
                        "vcodec": "h264_omx",
                        "packetSize": 752,
                        "audio": true,
                        "debug": true
                    }
                }
            ],
            "platform": "Camera-ffmpeg"
        },

![Captura de pantalla 2020-07-20 a las 16 34 14](https://user-images.githubusercontent.com/68552221/87950019-0f1b0680-caa7-11ea-9f9f-8d0c9945e950.png)

[camlog.rtf.zip](https://github.com/Sunoo/homebridge-camera-ffmpeg/files/4948283/camlog.rtf.zip)

I´ts possible any help with this? Thanks in advance!

**Comment by Sunoo** [comment] 2020-07-20 14:52
The only recent change that could change this was the fix to prevent zombie ffmpeg processes, but from you log, I can see that's not happening.

The only real issue I see from the logs is that it takes a few seconds for FFmpeg to see a key frame, then once it does it drops a ton of frames. Are you sure your camera is operating correctly? Can you view the feed in VLC?

**Comment by bubez81** [comment] 2020-07-20 14:59
same problem, the only solution was to set 
"maxWidth": 640,
"maxHeight": 480,

**Comment by Sunoo** [comment] 2020-07-20 15:00
@bubez81 Interesting, I don’t see what setting a maximum image size would have any impact on streaming like that. Was there something in your log that made you think that could be the problem?

**Comment by llemtt** [comment] 2020-07-20 15:00
may I suggest that Live555 rtsp implementation is a little buggy at best and not fully interoperable with ffmpeg?

**Comment by bubez81** [comment] 2020-07-20 19:56
> @bubez81 Interesting, I don’t see what setting a maximum image size would have any impact on streaming like that. Was there something in your log that made you think that could be the problem?

Nope, I think the problem is a mix of time out and dumping frames

**Comment by GermanyP** [comment] 2020-07-20 20:29
> The only recent change that could change this was the fix to prevent zombie ffmpeg processes, but from you log, I can see that's not happening.
> 
> The only real issue I see from the logs is that it takes a few seconds for FFmpeg to see a key frame, then once it does it drops a ton of frames. Are you sure your camera is operating correctly? Can you view the feed in VLC?

Thanks for your answer!
the stream in VLC plays fine, i tested 10 minutes with no issues...

**Comment by GermanyP** [comment] 2020-07-20 20:32
> same problem, the only solution was to set
> "maxWidth": 640,
> "maxHeight": 480,

I tested with same results :(

**Comment by lfiocco** [comment] 2020-07-22 01:07
I got this running on Ubuntu 20.04 on a VM, it's been rock solid for many years. However, I did notice that when you request a stream, it takes the FFMPEG server to display the string about 30-35 seconds to show up. Once it's on the display, The iPhone starts a few second later...

Any idea what could cause that? Why does it take so long for the string to appear once the request is sent?

**Comment by Sunoo** [comment] 2020-07-22 01:09
@lfiocco I’m really not sure. Can you provide your logs with debug turned on?

**Comment by lfiocco** [comment] 2020-07-22 01:17
I press the camera 2 tile at 9:12:29

[7/21/2020, 9:12:26 PM] [Camera-ffmpeg] Snapshot from Camera 1 - Front Door at 480:270
[7/21/2020, 9:12:29 PM] [Camera-ffmpeg] Snapshot from Camera 2 - Driveway at 480:270
[7/21/2020, 9:12:29 PM] [Camera-ffmpeg] Snapshot from Camera 3 - Side Door at 480:270
[7/21/2020, 9:12:38 PM] [Camera-ffmpeg] Snapshot from Camera 3 - Side Door at 480:270
[7/21/2020, 9:12:39 PM] [Camera-ffmpeg] Snapshot from Camera 4 - Backyard at 480:270
[7/21/2020, 9:12:47 PM] [Camera-ffmpeg] Snapshot from Camera 1 - Front Door at 480:270
[7/21/2020, 9:12:49 PM] [Camera-ffmpeg] Snapshot from Camera 4 - Backyard at 480:270
[7/21/2020, 9:12:58 PM] [Camera-ffmpeg] Starting Camera 2 - Driveway video stream (1280x720, 10 fps, 299 kbps, 1316 mtu)... 
[7/21/2020, 9:12:58 PM] [Camera-ffmpeg] Camera 2 - Driveway: received first frame
[7/21/2020, 9:13:13 PM] [Camera-ffmpeg] Snapshot from Camera 1 - Front Door at 480:270
[7/21/2020, 9:13:14 PM] [Camera-ffmpeg] Snapshot from Camera 3 - Side Door at 480:270
[7/21/2020, 9:13:18 PM] [Camera-ffmpeg] Camera 2 - Driveway appears to be inactive for over 5 seconds. Stopping stream.
[7/21/2020, 9:13:18 PM] [Camera-ffmpeg] Stopped Camera 2 - Driveway video stream!

**Comment by Sunoo** [comment] 2020-07-22 01:21
@lfiocco Unfortunately I don’t think there is anything I can to do help you there. When you see “Starting ... video stream” that’s when the plugin gets notified by HomeKit to start streaming. Not sure what’s going on with your network that causes that to be so delayed.

**Comment by lfiocco** [comment] 2020-07-22 01:34
ok, Thanks for the quick responds. I will check my communications, it's odd because i have my iPhone on the same network as my home automation systems. There is no firewall between. Does the same thing on the MacBook. Rebooted Apple TV same thing. I have a few other plugin's on the same Homebridge. I will spin up another VM with a clean install and run just the camera Plugin. See where that bring me. btw i am also installing 13.4.7 TVos right now. (Apple is pushing Covid-19 updates now?)

**Comment by lfiocco** [comment] 2020-07-22 01:53
No idea what just happened, Rebooted Apple TV, also installed update 13.4.7. Got it down to 12-13 seconds...

started 9:44:00,

[7/21/2020, 9:43:59 PM] [Camera-ffmpeg] Camera 3 - Side Door appears to be inactive for over 5 seconds. Stopping stream.
[7/21/2020, 9:43:59 PM] [Camera-ffmpeg] Stopped Camera 3 - Side Door video stream!
[7/21/2020, 9:44:04 PM] [Camera-ffmpeg] Snapshot from Camera 6 - Garage at 480:270
[7/21/2020, 9:44:13 PM] [Camera-ffmpeg] Stopped Camera 3 - Side Door video stream!
[7/21/2020, 9:44:14 PM] [Camera-ffmpeg] Starting Camera 4 - Backyard video stream (1280x720, 10 fps, 299 kbps, 1316 mtu)... 
[7/21/2020, 9:44:14 PM] [Camera-ffmpeg] Camera 4 - Backyard: received first frame

I will do some more troubleshooting, but it does not look like a problem with the plugin. 

Thanks again... Last year this time Apple was making some changes on their end. (IOS12 -> 13) Devices dropping and other issues. Might be related to mods to the eco-system to prep for the new IOS 14.. no idea. Last year I had to completely rebuild the Homekit Eco-System in my place, around this time...

**Comment by Sunoo** [comment] 2020-07-22 01:56
Great, I’ll close this out then. Good luck sorting out whatever is going on.

**Closed by Sunoo** 2020-07-22 01:56 UTC
